# Generated by Django 6.1 on 2026-09-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_is_publ_529169_idx',
            old_name='projects_pro_is_publ_a2d417_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_slug_042165_idx',
            old_name='projects_pro_slug_5af2d8_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_created_6b02e3_idx',
            old_name='projects_pro_created_7c7f75_idx',
        ),
        migrations.RenameIndex(
            model_name='projectimage',
            new_name='projects_pr_project_ccd929_idx',
            old_name='projects_pro_project_4a4aa7_idx',
        ),
        migrations.RenameIndex(
            model_name='projectsection',
            new_name='projects_pr_project_6d1489_idx',
            old_name='projects_pro_project_7d7c4c_idx',
        ),
    ]
