# Generated by Django 6.1 on 2026-10-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_pro_is_publ_a2d417_idx_projects_pr_is_publ_529169_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', max_length=80)),
                ('value', models.CharField(blank=True, default='', max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='projecthighlight',
            index=models.Index(fields=['project', 'order'], name='projects_pr_project_9f2aa0_idx'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='layout_type',
            field=models.CharField(choices=[('full_width_image', 'Full Width Image'), ('image_text_left', 'Image + Text Left'), ('image_text_right', 'Image + Text Right'), ('text_image', 'Text + Image'), ('two_column', 'Two Column'), ('large_banner', 'Large Banner')], default='image_text_right', max_length=30),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
