# Generated by Django 6.1.1 on 2026-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
