# Generated by Django 6.1.1 on 2026-09-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.AddField(
            model_name='abouthighlight',
            name='about',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
