# Generated by Django 6.1.1 on 2026-09-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_profile_about_abouthighlight_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthighlight',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
