from django.urls import path

from .admin_views import (
    AdminAboutAPIView,
    AdminAboutHighlightAPIView,
    AdminAboutHighlightDetailAPIView,
    AdminContactInfoAPIView,
    AdminDashboardOverviewAPIView,
    AdminEducationAPIView,
    AdminEducationDetailAPIView,
    AdminExperienceAPIView,
    AdminExperienceDetailAPIView,
    AdminMessageAPIView,
    AdminMessageDetailAPIView,
    AdminProfileAPIView,
    AdminProfileDetailAPIView,
    AdminProjectAPIView,
    AdminProjectDetailAPIView,
    AdminProjectImageAPIView,
    AdminProjectImageDetailAPIView,
    AdminProjectSectionAPIView,
    AdminProjectSectionDetailAPIView,
    AdminSkillAPIView,
    AdminSkillDetailAPIView,
    AdminSocialLinkAPIView,
    AdminSocialLinkDetailAPIView,
    AdminTechnologyAPIView,
    AdminTechnologyDetailAPIView,
    AdminTestimonialAPIView,
    AdminTestimonialDetailAPIView,
    AdminVisitorAPIView,
)

urlpatterns = [
    path('dashboard/', AdminDashboardOverviewAPIView.as_view(), name='admin-dashboard-overview'),
    path('profile/', AdminProfileAPIView.as_view(), name='admin-profile-list-create'),
    path('profile/<int:pk>/', AdminProfileDetailAPIView.as_view(), name='admin-profile-detail'),
    # hero endpoint removed; Hero content is managed via Profile
    path('about/', AdminAboutAPIView.as_view(), name='admin-about-list-create'),
    path('skills/', AdminSkillAPIView.as_view(), name='admin-skills-list-create'),
    path('skills/<int:pk>/', AdminSkillDetailAPIView.as_view(), name='admin-skills-detail'),
    path('social-links/', AdminSocialLinkAPIView.as_view(), name='admin-social-links-list-create'),
    path('social-links/<int:pk>/', AdminSocialLinkDetailAPIView.as_view(), name='admin-social-links-detail'),
    path('highlights/', AdminAboutHighlightAPIView.as_view(), name='admin-highlights-list-create'),
    path('highlights/<int:pk>/', AdminAboutHighlightDetailAPIView.as_view(), name='admin-highlights-detail'),
    path('experience/', AdminExperienceAPIView.as_view(), name='admin-experience-list-create'),
    path('experience/<int:pk>/', AdminExperienceDetailAPIView.as_view(), name='admin-experience-detail'),
    path('education/', AdminEducationAPIView.as_view(), name='admin-education-list-create'),
    path('education/<int:pk>/', AdminEducationDetailAPIView.as_view(), name='admin-education-detail'),
    path('testimonials/', AdminTestimonialAPIView.as_view(), name='admin-testimonials-list-create'),
    path('testimonials/<int:pk>/', AdminTestimonialDetailAPIView.as_view(), name='admin-testimonials-detail'),
    path('projects/', AdminProjectAPIView.as_view(), name='admin-projects-list-create'),
    path('projects/<slug:slug>/', AdminProjectDetailAPIView.as_view(), name='admin-projects-detail'),
    path('technologies/', AdminTechnologyAPIView.as_view(), name='admin-technologies-list-create'),
    path('technologies/<int:pk>/', AdminTechnologyDetailAPIView.as_view(), name='admin-technologies-detail'),
    path('project-images/', AdminProjectImageAPIView.as_view(), name='admin-project-images-list-create'),
    path('project-images/<int:pk>/', AdminProjectImageDetailAPIView.as_view(), name='admin-project-images-detail'),
    path('project-sections/', AdminProjectSectionAPIView.as_view(), name='admin-project-sections-list-create'),
    path('project-sections/<int:pk>/', AdminProjectSectionDetailAPIView.as_view(), name='admin-project-sections-detail'),
    path('messages/', AdminMessageAPIView.as_view(), name='admin-messages-list'),
    path('messages/<int:pk>/', AdminMessageDetailAPIView.as_view(), name='admin-messages-detail'),
    path('contact-information/', AdminContactInfoAPIView.as_view(), name='admin-contact-information'),
    path('visitors/', AdminVisitorAPIView.as_view(), name='admin-visitors-list'),
]
